[package]
name = "woodpecker"
version = "0.1.0"
authors = ["Ferran Basora <fcsonline@gmail.com>"]

[dependencies]
time = "0.1.37"
regex = "0.2.1"
yaml-rust = "0.3.5"
hyper = "0.10"
serde_json = "1.0.2"
colored = "^1.5"
csv = "1.0.0-beta.3"
