[package]
name = "drill"
version = "0.5.0"
authors = ["Ferran Basora <fcsonline@gmail.com>"]
description = "Drill is a HTTP load testing application written in Rust inspired by Ansible syntax"
repository = "https://github.com/fcsonline/drill"
keywords = ["performance", "http", "ansible", "jmeter"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
clap = "2.32.0"
colored = "1.7.0"
csv = "1.0.5"
hyper = "0.12.25"
hyper-tls = "0.3.2"
regex = "1.1.2"
serde_json = "1.0.39"
time = "0.1.42"
yaml-rust = "0.4.3"
linked-hash-map = "0.5.2"

futures = "0.1.25"
tokio = "0.1.15"
tokio-scoped = "0.1.0"

futures-timer = "0.1"
