[package]
name = "drill"
version = "0.4.1"
authors = ["Ferran Basora <fcsonline@gmail.com>"]
description = "Drill is a HTTP load testing application written in Rust inspired by Ansible syntax"
repository = "https://github.com/fcsonline/drill"
keywords = ["performance", "http", "ansible", "jmeter"]
license = "GPL-3.0"

[dependencies]
clap = "2.24.2"
colored = "^1.5"
csv = "1.0.0-beta.3"
hyper = "0.10.13"
hyper-native-tls = "0.2.3"
regex = "0.2.1"
serde_json = "1.0.2"
time = "0.1.37"
yaml-rust = "0.3.5"
sxd-xpath = "0.4.2"
sxd-document = "0.3.0"

[[bin]]
name = "drill"
path = "src/main.rs"

[[bin]]
name = "jmeter2drill"
path = "src/jmeter2drill/main.rs"
